/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as OwnerIndexRouteImport } from './routes/owner/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as OwnerServicesRouteImport } from './routes/owner/services'
import { Route as OwnerReviewsRouteImport } from './routes/owner/reviews'
import { Route as OwnerReportsRouteImport } from './routes/owner/reports'
import { Route as OwnerPromotionsRouteImport } from './routes/owner/promotions'
import { Route as OwnerProfileRouteImport } from './routes/owner/profile'
import { Route as OwnerHoursRouteImport } from './routes/owner/hours'
import { Route as OwnerAgendaRouteImport } from './routes/owner/agenda'
import { Route as CustomerReviewsRouteImport } from './routes/customer/reviews'
import { Route as CustomerMeRouteImport } from './routes/customer/me'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminBusinessesRouteImport } from './routes/admin/businesses'
import { Route as AdminAdministratorsRouteImport } from './routes/admin/administrators'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as PublicBusinessesIndexRouteImport } from './routes/_public/businesses.index'
import { Route as PublicBusinessesBusinessIdRouteImport } from './routes/_public/businesses.$businessId'
import { Route as CustomerBookBusinessIdServiceIdRouteImport } from './routes/customer/book.$businessId.$serviceId'

const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const OwnerServicesRoute = OwnerServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerReviewsRoute = OwnerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerReportsRoute = OwnerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPromotionsRoute = OwnerPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerProfileRoute = OwnerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerHoursRoute = OwnerHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAgendaRoute = OwnerAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => OwnerRoute,
} as any)
const CustomerReviewsRoute = CustomerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerMeRoute = CustomerMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessesRoute = AdminBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdministratorsRoute = AdminAdministratorsRouteImport.update({
  id: '/administrators',
  path: '/administrators',
  getParentRoute: () => AdminRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PublicBusinessesIndexRoute = PublicBusinessesIndexRouteImport.update({
  id: '/businesses/',
  path: '/businesses/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBusinessesBusinessIdRoute =
  PublicBusinessesBusinessIdRouteImport.update({
    id: '/businesses/$businessId',
    path: '/businesses/$businessId',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const CustomerBookBusinessIdServiceIdRoute =
  CustomerBookBusinessIdServiceIdRouteImport.update({
    id: '/book/$businessId/$serviceId',
    path: '/book/$businessId/$serviceId',
    getParentRoute: () => CustomerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/owner': typeof OwnerRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/admin/administrators': typeof AdminAdministratorsRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/customer/me': typeof CustomerMeRoute
  '/customer/reviews': typeof CustomerReviewsRoute
  '/owner/agenda': typeof OwnerAgendaRoute
  '/owner/hours': typeof OwnerHoursRoute
  '/owner/profile': typeof OwnerProfileRoute
  '/owner/promotions': typeof OwnerPromotionsRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/reviews': typeof OwnerReviewsRoute
  '/owner/services': typeof OwnerServicesRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/businesses/$businessId': typeof PublicBusinessesBusinessIdRoute
  '/businesses/': typeof PublicBusinessesIndexRoute
  '/customer/book/$businessId/$serviceId': typeof CustomerBookBusinessIdServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/admin/administrators': typeof AdminAdministratorsRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/customer/me': typeof CustomerMeRoute
  '/customer/reviews': typeof CustomerReviewsRoute
  '/owner/agenda': typeof OwnerAgendaRoute
  '/owner/hours': typeof OwnerHoursRoute
  '/owner/profile': typeof OwnerProfileRoute
  '/owner/promotions': typeof OwnerPromotionsRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/reviews': typeof OwnerReviewsRoute
  '/owner/services': typeof OwnerServicesRoute
  '/admin': typeof AdminIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/businesses/$businessId': typeof PublicBusinessesBusinessIdRoute
  '/businesses': typeof PublicBusinessesIndexRoute
  '/customer/book/$businessId/$serviceId': typeof CustomerBookBusinessIdServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/owner': typeof OwnerRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/admin/administrators': typeof AdminAdministratorsRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/customer/me': typeof CustomerMeRoute
  '/customer/reviews': typeof CustomerReviewsRoute
  '/owner/agenda': typeof OwnerAgendaRoute
  '/owner/hours': typeof OwnerHoursRoute
  '/owner/profile': typeof OwnerProfileRoute
  '/owner/promotions': typeof OwnerPromotionsRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/reviews': typeof OwnerReviewsRoute
  '/owner/services': typeof OwnerServicesRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/_public/businesses/$businessId': typeof PublicBusinessesBusinessIdRoute
  '/_public/businesses/': typeof PublicBusinessesIndexRoute
  '/customer/book/$businessId/$serviceId': typeof CustomerBookBusinessIdServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customer'
    | '/owner'
    | '/login'
    | '/signup'
    | '/admin/administrators'
    | '/admin/businesses'
    | '/admin/customers'
    | '/customer/me'
    | '/customer/reviews'
    | '/owner/agenda'
    | '/owner/hours'
    | '/owner/profile'
    | '/owner/promotions'
    | '/owner/reports'
    | '/owner/reviews'
    | '/owner/services'
    | '/admin/'
    | '/owner/'
    | '/businesses/$businessId'
    | '/businesses/'
    | '/customer/book/$businessId/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer'
    | '/login'
    | '/signup'
    | '/admin/administrators'
    | '/admin/businesses'
    | '/admin/customers'
    | '/customer/me'
    | '/customer/reviews'
    | '/owner/agenda'
    | '/owner/hours'
    | '/owner/profile'
    | '/owner/promotions'
    | '/owner/reports'
    | '/owner/reviews'
    | '/owner/services'
    | '/admin'
    | '/owner'
    | '/businesses/$businessId'
    | '/businesses'
    | '/customer/book/$businessId/$serviceId'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/admin'
    | '/customer'
    | '/owner'
    | '/_auth/login'
    | '/_auth/signup'
    | '/admin/administrators'
    | '/admin/businesses'
    | '/admin/customers'
    | '/customer/me'
    | '/customer/reviews'
    | '/owner/agenda'
    | '/owner/hours'
    | '/owner/profile'
    | '/owner/promotions'
    | '/owner/reports'
    | '/owner/reviews'
    | '/owner/services'
    | '/_public/'
    | '/admin/'
    | '/owner/'
    | '/_public/businesses/$businessId'
    | '/_public/businesses/'
    | '/customer/book/$businessId/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  OwnerRoute: typeof OwnerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/owner/services': {
      id: '/owner/services'
      path: '/services'
      fullPath: '/owner/services'
      preLoaderRoute: typeof OwnerServicesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/reviews': {
      id: '/owner/reviews'
      path: '/reviews'
      fullPath: '/owner/reviews'
      preLoaderRoute: typeof OwnerReviewsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/reports': {
      id: '/owner/reports'
      path: '/reports'
      fullPath: '/owner/reports'
      preLoaderRoute: typeof OwnerReportsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/promotions': {
      id: '/owner/promotions'
      path: '/promotions'
      fullPath: '/owner/promotions'
      preLoaderRoute: typeof OwnerPromotionsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/profile': {
      id: '/owner/profile'
      path: '/profile'
      fullPath: '/owner/profile'
      preLoaderRoute: typeof OwnerProfileRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/hours': {
      id: '/owner/hours'
      path: '/hours'
      fullPath: '/owner/hours'
      preLoaderRoute: typeof OwnerHoursRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/agenda': {
      id: '/owner/agenda'
      path: '/agenda'
      fullPath: '/owner/agenda'
      preLoaderRoute: typeof OwnerAgendaRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/customer/reviews': {
      id: '/customer/reviews'
      path: '/reviews'
      fullPath: '/customer/reviews'
      preLoaderRoute: typeof CustomerReviewsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/me': {
      id: '/customer/me'
      path: '/me'
      fullPath: '/customer/me'
      preLoaderRoute: typeof CustomerMeRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/businesses': {
      id: '/admin/businesses'
      path: '/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AdminBusinessesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administrators': {
      id: '/admin/administrators'
      path: '/administrators'
      fullPath: '/admin/administrators'
      preLoaderRoute: typeof AdminAdministratorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_public/businesses/': {
      id: '/_public/businesses/'
      path: '/businesses'
      fullPath: '/businesses/'
      preLoaderRoute: typeof PublicBusinessesIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/businesses/$businessId': {
      id: '/_public/businesses/$businessId'
      path: '/businesses/$businessId'
      fullPath: '/businesses/$businessId'
      preLoaderRoute: typeof PublicBusinessesBusinessIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/customer/book/$businessId/$serviceId': {
      id: '/customer/book/$businessId/$serviceId'
      path: '/book/$businessId/$serviceId'
      fullPath: '/customer/book/$businessId/$serviceId'
      preLoaderRoute: typeof CustomerBookBusinessIdServiceIdRouteImport
      parentRoute: typeof CustomerRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBusinessesBusinessIdRoute: typeof PublicBusinessesBusinessIdRoute
  PublicBusinessesIndexRoute: typeof PublicBusinessesIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicBusinessesBusinessIdRoute: PublicBusinessesBusinessIdRoute,
  PublicBusinessesIndexRoute: PublicBusinessesIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AdminRouteChildren {
  AdminAdministratorsRoute: typeof AdminAdministratorsRoute
  AdminBusinessesRoute: typeof AdminBusinessesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdministratorsRoute: AdminAdministratorsRoute,
  AdminBusinessesRoute: AdminBusinessesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomerRouteChildren {
  CustomerMeRoute: typeof CustomerMeRoute
  CustomerReviewsRoute: typeof CustomerReviewsRoute
  CustomerBookBusinessIdServiceIdRoute: typeof CustomerBookBusinessIdServiceIdRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerMeRoute: CustomerMeRoute,
  CustomerReviewsRoute: CustomerReviewsRoute,
  CustomerBookBusinessIdServiceIdRoute: CustomerBookBusinessIdServiceIdRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface OwnerRouteChildren {
  OwnerAgendaRoute: typeof OwnerAgendaRoute
  OwnerHoursRoute: typeof OwnerHoursRoute
  OwnerProfileRoute: typeof OwnerProfileRoute
  OwnerPromotionsRoute: typeof OwnerPromotionsRoute
  OwnerReportsRoute: typeof OwnerReportsRoute
  OwnerReviewsRoute: typeof OwnerReviewsRoute
  OwnerServicesRoute: typeof OwnerServicesRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerAgendaRoute: OwnerAgendaRoute,
  OwnerHoursRoute: OwnerHoursRoute,
  OwnerProfileRoute: OwnerProfileRoute,
  OwnerPromotionsRoute: OwnerPromotionsRoute,
  OwnerReportsRoute: OwnerReportsRoute,
  OwnerReviewsRoute: OwnerReviewsRoute,
  OwnerServicesRoute: OwnerServicesRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  OwnerRoute: OwnerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
